### ISSUE TITLE
User Delete Function doesn't work

### ISSUE THREAD

**Issue by Visilink** [DavelBM/ProductionEnvironment#56]
I see a list of users, but can't delete or otherwise modify a user's attributes. The site-admin should be able to do this function... as should individual users on their own profiles.
![2018-06-30_9-13-00](https://user-images.githubusercontent.com/39421656/42126515-32187d94-7c47-11e8-8628-34e200d8e21c.jpg)

**Comment by alvidales** [comment]
This was reopened because sorting features were not implemented.

**Comment by mastorgal** [comment]
Need designs of the sorting and the show fields ability. Will try to implement something in the meantime.

**Comment by alvidales** [comment]
- [x] The search field works, when clicked on desired user after search it opens another tab for editing the user, I expected the table below to be filtered in order to do further actions (edit or delete).
- [ ] Sort users is not working.
- [x] Delete function works!!.
- [ ] Show/hide optional fields on users list not done.

**Comment by mastorgal** [comment]
@alvidales 
Cannot make the sort ability to work using a Drupal friendly way, we will have to change the way we built the list. Currently we use views with a plugin called Infinite Scroll, I tried to add the sorting method from Views but it does not show up.

I do not know what Show/hide option fields is.

Notes:
I have added the administrator users to the list and removed the edit/delete actions from them.
