### ISSUE TITLE
User Role Management

### ISSUE THREAD

**Issue by Visilink** [DavelBM/ProductionEnvironment#58]
The user management area needs to show user roles in addition to the channels they can access. What role does each user have? Is it the same?

I'm logged in as lorand@gmail.com... but I'm not clear what user is assigned to me, with the site_admin role. Or if it is, it isn't clear which user or users have the site_admin role.

Please make this clearly visible.

**Comment by Visilink** [comment]
![2018-06-30_9-27-39](https://user-images.githubusercontent.com/39421656/42126661-5856837e-7c48-11e8-965f-e77d48a936e9.jpg)

**Comment by mastorgal** [comment]
We have changed the username and it is now displaying the e-mail instead, 2nd column are the roles of the user, not channels they have access to, 3rd column are the actions on the user

Additionally, administrator/site_admin users are not displayed in the list as they can be accidentally deleted or we can remove the action buttons on these users if they need to be in the list

Probably we can add headers to the "table" so users can know it is actually a role (group) instead of a taxonomy (channel)
